### ISSUE TITLE
Re-use `HandlerStack` if set in options

### ISSUE THREAD

**Issue by arubacao** [GrahamCampbell/Guzzle-Factory#2]
I use this library for almost every guzzle client, however, I sometimes need more middleware on my HandlerStack than only the retry functionality.
That's why I purpose a re-usage of the `handler` passed in the `options` array through the [`make`](https://github.com/GrahamCampbell/Guzzle-Factory/blob/v2.2.0/src/GuzzleFactory.php#L68) method.
Currently, the passed in handler overrides the generated handler.
So: 
1. Check if `handler` is set in `options` array & `handler` is of correct type
2a. Re-use this `HandlerStack` object
2b. Instantiate new `HandlerStack` object

Cheers,
Chris

**Comment by GrahamCampbell** [comment]
Sounds possible, yeh.

**Comment by GrahamCampbell** [comment]
@arubacao Does https://github.com/GrahamCampbell/Guzzle-Factory/pull/3 do what you want?

**Comment by arubacao** [comment]
@GrahamCampbell awesome, thanks :)

**Comment by GrahamCampbell** [comment]
Will be released as v3.0.0.
